.DEFAULT_GOAL := help
IMG_NAME ?= {{img_name}}

define prompt_cmd
@ read -e -p " " -i "$(1)"  CMDtoEXECUTE; $$CMDtoEXECUTE
endef

{% if docker_type %}###### Docker ######{% endif %}
{% if 'cpu' in docker_type %}
docker-build: ## Build the Docker img
	$(call prompt_cmd,\
	docker build -t $(IMG_NAME) -f ./Docker/Dockerfile .\
	)


docker-run: ## Run the Docker container
	$(call prompt_cmd,\
	docker run --rm -it -v .:/project \
	--name $(IMG_NAME) $(IMG_NAME)\
	)


docker-bash: ## Access container bash
	$(call prompt_cmd,\
	docker exec -it $(IMG_NAME) /bin/bash\
	)

docker-clean: ## Remove Docker img
	$(call prompt_cmd,\
	docker rmi $(IMG_NAME)\
	)
{% endif %}
{% if 'gpu' in docker_type %}
docker-build-gpu: ## Build the Docker img [gpu]
	$(call prompt_cmd,\
	docker build -t $(IMG_NAME)-gpu -f ./Docker/gpu/Dockerfile .\
	)


docker-run-gpu: ## Run the Docker container [gpu]
	$(call prompt_cmd,\
	docker run --rm -it --runtime=nvidia --gpus all -v .:/project \
	--name $(IMG_NAME)-gpu $(IMG_NAME)-gpu\
	)


docker-bash-gpu: ## Access container bash [gpu]
	$(call prompt_cmd,\
	docker exec -it $(IMG_NAME)-gpu /bin/bash\
	)

docker-clean-gpu: ## Remove Docker img [gpu]
	$(call prompt_cmd,\
	docker rmi $(IMG_NAME)-gpu\
	)
{% endif %}


###### Project ######

dev-install: ## uv sync
	$(call prompt_cmd,\
	uv sync --all-groups\
	)

lint: ## Run linter [dev]
	$(call prompt_cmd,\
	uv run ruff check .\
	)

format: ## Run formatter [dev]
	$(call prompt_cmd,\
	uv run ruff format --diff .\
	)

tox-rerun: ## Launch Tox [dev, tox]
	$(call prompt_cmd,\
	uv run tox --parallel\
	)

tox-run: ## Launch Tox [dev, tox]
	$(call prompt_cmd,\
	uv run tox -r --parallel\
	)

test: ## Pytest with coverage
	$(call prompt_cmd,\
	uv run pytest --cov --durations=5 --color=yes\
	)

pre-commit: ## Run pre-commit
	$(call prompt_cmd,\
	uv run pre-commit run --all-files --show-diff-on-failure\
	)

pre-commit-enforce: ## Install the pre-commit as a git hook (you can just run pre-commit without doing that by: `make pre-commit`)
	$(call prompt_cmd,\
	uv run pre-commit install\
	)

update-pre-commit-hooks: ## Update automatically the hooks for `pre-commit`
	$(call prompt_cmd,\
	uv run pre-commit autoupdate\
	)


###### Docs ######

docs-build: ## Build docs
	{% if doc_tool == 'mkdocs' -%}
	$(call prompt_cmd,\
	uv run mkdocs build\
	)
	{% endif %}
	{% if doc_tool == 'sphinx' -%}
	$(call prompt_cmd,\
	echo "Not implemented"\
	)
	{% endif %}

docs-deploy: ## Deploy docs
	{% if doc_tool == 'mkdocs' -%}
	$(call prompt_cmd,\
	uv run mkdocs serve\
	)
	{% endif %}
	{% if doc_tool == 'sphinx' -%}
	$(call prompt_cmd,\
	echo "Not implemented"\
	)
	{% endif %}

docs-docker-build: ## Build docs using Docker container
	{% if doc_tool == 'mkdocs' -%}
	$(call prompt_cmd,\
	docker run --rm -it -v .:/project \
	--name $(IMG_NAME)-docs $(IMG_NAME) /bin/bash -c "cd project; uv sync --only-group mkdocs; uv run mkdocs build"\
	)
	{% endif %}


docs-docker-serve: ## Build docs using Docker container
	{% if doc_tool == 'mkdocs' -%}
	$(call prompt_cmd,\
	docker run --rm -it -v .:/project -p 8000:8000 \
	--name $(IMG_NAME)-docs $(IMG_NAME) /bin/bash -c  "cd project; uv sync --only-group mkdocs; uv run mkdocs serve -a 0.0.0.0:8000"\
	)
	{% endif %}


###### Help ######

# https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
.PHONY: help

help:
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

